### ISSUE TITLE
S3 bucket creating error when I start q1-openworld

### ISSUE THREAD

**Issue by nynuz** [stafordtituss/HazProne#1]
Hi, I buy your course on AWS (pentestmag) and when when I try to create q1-openworld to ask to (W43A01) exercise i get the error below:

```
Error: Error creating S3 bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
status code: 409, request id: 78CB89AB3C2FF937, host id: rZaPowBMcb9gZ72gYKUgI4u6Gz2ORgZwokpJy++vnhbXBzDZOyHeCUC9bRimN0/0tRiDqKAF9mU=

HAZPRONE :: Error Code returned by Terraform. Please try again!!

HAZPRONE :: Deleting Quest Folder!!
```

Then if I try to recreate q1-openworld it say me that some resources already exist and that I have to delete them manually but for example dynamodb table not exists in my dynamodb dashboard.
I have used a new AWS free tier account and I also try with a new AWS Account but I get the same erorr.

Thank You!

**Comment by stafordtituss** [comment]
Yes, the error has now been fixed. It was due to an update where Amazon had made S3 bucket names global hence, I’ve now configured the bucket names to be dynamic!
